---

name: build

on:
  workflow_call:
    secrets:
      do-token:
        description: 'Digital Ocean access token'
        required: true
      registry:
        description: 'Digital Ocean Container Registry'
        required: true

jobs:
  build_fastapi_example_backend:
    runs-on: ubuntu-latest
    name: Build fastapi_example_backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.do-token }}
      - name: Build fastapi_example_backend
        run: |
          docker build --build-arg env=staging -t ${{ secrets.registry }}/fastapi_example_backend:${{ github.sha }} ./fastapi_example_backend
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.registry }}/fastapi_example_backend:${{ github.sha }}

  build_fastapi_example_nginx:
    runs-on: ubuntu-latest
    name: Build Nginx proxy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.do-token }}
      - name: Build fastapi_example_nginx
        run: |
          docker build --build-arg env=staging -t ${{ secrets.registry }}/fastapi_example_nginx:${{ github.sha }} ./fastapi_example_nginx
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.registry }}/fastapi_example_nginx:${{ github.sha }}
